jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Update and Install SQLite
      run: |
        sudo apt-get update
        sudo apt-get install -y sqlite3 libsqlite3-dev
        sqlite3 --version  # Check that it's updated

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt
