name: Build and Deploy Streamlit App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SQLite
        run: |
          sudo apt update
          sudo apt install -y sqlite3 libsqlite3-dev
          sqlite3 --version

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # Or any specific version you need

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Streamlit
        run: |
          streamlit run app.py --server.enableCORS false --server.enableXsrfProtection false
