jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install SQLite
      run: |
        sudo apt update
        sudo apt install -y sqlite3 libsqlite3-dev
        sqlite3 --version

    - name: Install Python dependencies
      run: pip install -r requirements.txt

    - name: Run Streamlit
      run: streamlit run app.py
